AWSTemplateFormatVersion: '2020-11-29'
Description: 'study-datalake

  Rest API

  '
Globals:
  Function:
    MemorySize: 512
    Timeout: 20
Outputs:
  CreateStudyRecordFunction:
    Description: CreateTripRecord Lambda Function ARN
    Value:
      Fn::GetAtt:
      - CreateTripRecordFunction
      - Arn