AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'study-datalake Rest API to manage a Data Lake of study links

  '
Globals:
  Function:
    Timeout: 100
    MemorySize: 256
    Environment:
      Variables:
        TABLE_NAME:
          Ref: StudyTable
        ENDPOINT_OVERRIDE: ''
Parameters:
  CognitoUsePoolARN:
    Type: String
    Default: arn:aws:cognito-idp:us-east-1:729449663161:userpool/us-east-1_6qFmqyEYn
Resources:
  APIGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      EndpointConfiguration: REGIONAL
      Auth:
        DefaultAuthorizer: MyCognitoAuth
        Authorizers:
          MyCognitoAuth:
            UserPoolArn:
              Ref: CognitoUsePoolARN
            Identity:
              Header: Authorization
              ReauthorizeEvery: 30
  CreateStudyRecordFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://sam-mb-dev-deploy/f37d75b7451d3c873c0a6430ea8f256f
      Handler: br.com.iwe.handler.CreateStudyRecord::handleRequest
      Runtime: java8
      Tracing: Active
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: StudyTable
      Events:
        CreateStudyRecord:
          Type: Api
          Properties:
            RestApiId:
              Ref: APIGateway
            Path: /study
            Method: post
  GetStudyRecordsByPeriodFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://sam-mb-dev-deploy/f37d75b7451d3c873c0a6430ea8f256f
      Handler: br.com.iwe.handler.GetStudyRecordsByPeriod::handleRequest
      Runtime: java8
      Tracing: Active
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: StudyTable
      Events:
        GetStudyRecordsByPeriod:
          Type: Api
          Properties:
            RestApiId:
              Ref: APIGateway
            Path: /study/{topic}/findByPeriod
            Method: get
            RequestParameters:
            - method.request.querystring.starts
            - method.request.querystring.ends
  GetStudyRecordsByTagFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://sam-mb-dev-deploy/f37d75b7451d3c873c0a6430ea8f256f
      Handler: br.com.iwe.handler.GetStudyRecordsByTag::handleRequest
      Runtime: java8
      Tracing: Active
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: StudyTable
      Events:
        GetStudyRecordsByTag:
          Type: Api
          Properties:
            RestApiId:
              Ref: APIGateway
            Path: /study/{topic}/findByTag
            Method: get
            RequestParameters:
            - method.request.querystring.tag
  GetStudyRecordsByIsConsumedFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://sam-mb-dev-deploy/f37d75b7451d3c873c0a6430ea8f256f
      Handler: br.com.iwe.handler.GetStudyRecordsByIsConsumed::handleRequest
      Runtime: java8
      Tracing: Active
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: StudyTable
      Events:
        GetStudyRecordsByIsConsumed:
          Type: Api
          Properties:
            RestApiId:
              Ref: APIGateway
            Path: /study/{topic}/findByIsConsumed
            Method: get
            RequestParameters:
            - method.request.querystring.isconsumed
  StudyTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Study
      AttributeDefinitions:
      - AttributeName: topic
        AttributeType: S
      - AttributeName: dateTimeCreation
        AttributeType: S
      - AttributeName: tag
        AttributeType: S
      - AttributeName: consumed
        AttributeType: S
      KeySchema:
      - AttributeName: topic
        KeyType: HASH
      - AttributeName: dateTimeCreation
        KeyType: RANGE
      LocalSecondaryIndexes:
      - IndexName: tagIndex
        KeySchema:
        - AttributeName: topic
          KeyType: HASH
        - AttributeName: tag
          KeyType: RANGE
        Projection:
          ProjectionType: ALL
      - IndexName: consumedIndex
        KeySchema:
        - AttributeName: topic
          KeyType: HASH
        - AttributeName: consumed
          KeyType: RANGE
        Projection:
          ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST
Outputs:
  CreateStudyRecordFunction:
    Description: CreateStudyRecord Lambda Function ARN
    Value:
      Fn::GetAtt:
      - CreateStudyRecordFunction
      - Arn
  GetStudyRecordsByPeriodFunction:
    Description: GetStudyRecordsByPeriod Lambda Function ARN
    Value:
      Fn::GetAtt:
      - GetStudyRecordsByPeriodFunction
      - Arn
  GetStudyRecordsByTagFunction:
    Description: GetStudyRecordsByTag Lambda Function ARN
    Value:
      Fn::GetAtt:
      - GetStudyRecordsByTagFunction
      - Arn
  GetStudyRecordsByIsConsumedFunction:
    Description: GetStudyRecordsByIsConsumed Lambda Function ARN
    Value:
      Fn::GetAtt:
      - GetStudyRecordsByIsConsumedFunction
      - Arn
