AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'study-datalake Rest API to manage a Data Lake of study links

  '
Globals:
  Function:
    Timeout: 110
    MemorySize: 512
    Environment:
      Variables:
        TABLE_NAME:
          Ref: StudyTable
        ENDPOINT_OVERRIDE: ''
Resources:
  APIGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      EndpointConfiguration: REGIONAL
      TracingEnabled: true
  CreateStudyRecordFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://sam-advdev-deploy/9d2f8ece9f7c7043b86c74ebad627a41
      Handler: br.com.iwe.handler.CreateStudyRecord::handleRequest
      Runtime: java8
      Tracing: Active
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: StudyTable
      Events:
        CreateStudyRecord:
          Type: Api
          Properties:
            RestApiId:
              Ref: APIGateway
            Path: /study
            Method: post
  GetStudyRecordsByPeriodFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://sam-advdev-deploy/9d2f8ece9f7c7043b86c74ebad627a41
      Handler: br.com.iwe.handler.GetStudyRecordsByPeriod::handleRequest
      Runtime: java8
      Tracing: Active
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: StudyTable
      Events:
        GetStudyRecordsByPeriod:
          Type: Api
          Properties:
            RestApiId:
              Ref: APIGateway
            Path: /study/{topic}/findByPeriod
            Method: get
            RequestParameters:
            - method.request.querystring.starts
            - method.request.querystring.ends
  GetStudyRecordsByTagFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://sam-advdev-deploy/9d2f8ece9f7c7043b86c74ebad627a41
      Handler: br.com.iwe.handler.GetStudyRecordsByTag::handleRequest
      Runtime: java8
      Tracing: Active
      AutoPublishAlias: live
      DeploymentPreference:
        Type: Canary10Percent5Minutes
      Environment:
        Variables:
          AWS_CODEGURU_PROFILER_GROUP_ARN: arn:aws:codeguru-profiler:us-west-2:449795832125:profilingGroup/StudyDataLake
          AWS_CODEGURU_PROFILER_ENABLED: true
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: StudyTable
      Events:
        GetStudyRecordsByTag:
          Type: Api
          Properties:
            RestApiId:
              Ref: APIGateway
            Path: /study/{topic}/findByTag
            Method: get
            RequestParameters:
            - method.request.querystring.tag
  GetStudyRecordsByIsConsumedFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://sam-advdev-deploy/9d2f8ece9f7c7043b86c74ebad627a41
      Handler: br.com.iwe.handler.GetStudyRecordsByIsConsumed::handleRequest
      Runtime: java8
      Tracing: Active
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: StudyTable
      Events:
        GetStudyRecordsByIsConsumed:
          Type: Api
          Properties:
            RestApiId:
              Ref: APIGateway
            Path: /study/{topic}/findByIsConsumed
            Method: get
            RequestParameters:
            - method.request.querystring.isconsumed
  StudyTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Study
      AttributeDefinitions:
      - AttributeName: topic
        AttributeType: S
      - AttributeName: dateTimeCreation
        AttributeType: S
      - AttributeName: tag
        AttributeType: S
      - AttributeName: consumed
        AttributeType: S
      KeySchema:
      - AttributeName: topic
        KeyType: HASH
      - AttributeName: dateTimeCreation
        KeyType: RANGE
      LocalSecondaryIndexes:
      - IndexName: tagIndex
        KeySchema:
        - AttributeName: topic
          KeyType: HASH
        - AttributeName: tag
          KeyType: RANGE
        Projection:
          ProjectionType: ALL
      - IndexName: consumedIndex
        KeySchema:
        - AttributeName: topic
          KeyType: HASH
        - AttributeName: consumed
          KeyType: RANGE
        Projection:
          ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST
Outputs:
  CreateStudyRecordFunction:
    Description: CreateStudyRecord Lambda Function ARN
    Value:
      Fn::GetAtt:
      - CreateStudyRecordFunction
      - Arn
  GetStudyRecordsByPeriodFunction:
    Description: GetStudyRecordsByPeriod Lambda Function ARN
    Value:
      Fn::GetAtt:
      - GetStudyRecordsByPeriodFunction
      - Arn
  GetStudyRecordsByTagFunction:
    Description: GetStudyRecordsByTag Lambda Function ARN
    Value:
      Fn::GetAtt:
      - GetStudyRecordsByTagFunction
      - Arn
  GetStudyRecordsByIsConsumedFunction:
    Description: GetStudyRecordsByIsConsumed Lambda Function ARN
    Value:
      Fn::GetAtt:
      - GetStudyRecordsByIsConsumedFunction
      - Arn
