AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    study-datalake

    Rest API to manage a Data Lake of study links

Globals:
    Function:
        Timeout: 20
        MemorySize: 512
        Environment:
          Variables:
            TABLE_NAME: !Ref StudyTable
            ENDPOINT_OVERRIDE: ""

Resources:

  CreateTripRecordFunction:
    Type: AWS::Serverless::Function
    Properties:
     CodeUri: target/study-datalake-1.0.0-SNAPSHOT-jar-with-dependencies.jar
     Handler: br.com.iwe.handler.CreateTripRecord::handleRequest
     Runtime: java8
     Policies:
       - DynamoDBCrudPolicy:
           TableName: !Ref Trip
     Events:
       CreateStudyRecord:
         Type: Api
         Properties:
           Path: /Trip
           Method: post
              
  StudyTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: trip
      AttributeDefinitions:
        - AttributeName: country
          AttributeType: S
        - AttributeName: city
          AttributeType: S
        - AttributeName: date
          AttributeType: S
        - AttributeName: reason
          AttributeType: S            
      KeySchema:
        - AttributeName: country
          KeyType: HASH
        - AttributeName: date
          KeyType: RANGE
      LocalSecondaryIndexes: 
        - IndexName: cityIndex
          KeySchema: 
            - AttributeName: country
              KeyType: HASH
            - AttributeName: city
              KeyType: RANGE
          Projection:
             ProjectionType: ALL 
        - IndexName: reasonIndex
          KeySchema: 
            - AttributeName: country
              KeyType: HASH
            - AttributeName: reason
              KeyType: RANGE
          Projection:
             ProjectionType: ALL      
      BillingMode: PAY_PER_REQUEST              

Outputs:

    CreateTripRecordFunction:
      Description: "CreateTripRecord Lambda Function ARN"
      Value: !GetAtt CreateTripRecordFunction.Arn
